Updated Create Survey Page
Blargie/SYSC4806FinalProject pull request #13
Opened 2024-11-22 19:59 UTC by lucaswhitaker22

- Added some extra fields to create survey page (description, expiration, anonymous, required/optional toggle for questions)
- removed the "Correct Answer" component from MultipleChoiceQuestion

![image](https://github.com/user-attachments/assets/44dd8d77-848b-4db2-8d7d-e7560c7e9ec4)

2024-11-22 22:33 UTC, Keegan9049 approved these changes

2024-11-22 23:43 UTC, Blargie requested changes
Please look into the issue where answering a survey doesn't properly record answers/forward the correct page.

2024-11-24 19:30 UTC, MohannadDukhan approved these changes

2024-11-24 20:11 UTC, Blargie reviewed
All good

2024-11-24 20:11 UTC, merged